<a href="https://colab.research.google.com/github/aneesa-basheer/Data-Science-LAB/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [8]:
a = np.array([[1,2],[3,4]])
b = np.arange(15)
c = np.arange(4).reshape(2,2)
print (a)
print (b)
print (c)

[[1 2]
 [3 4]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[0 1]
 [2 3]]


In [11]:
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [12]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4
