<a href="https://colab.research.google.com/github/aneesa-basheer/Data-Science-LAB/blob/main/Program1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [7]:
array_from_list=np.array([1,2,3,4,5])
print("Array from list :",array_from_list)

array_with_range=np.arange(10)
print("Array with range:",array_with_range)

zeros_array=np.zeros((3,3))
print("Zeros array:\n",zeros_array)

ones_array=np.ones((3,3))
print("Ones array:\n",ones_array)


Array from list : [1 2 3 4 5]
Array with range: [0 1 2 3 4 5 6 7 8 9]
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [14]:
array=np.arange(12)
print("orginal array:",array)

reshaped_array=array.reshape(3,4)
print("Reshaped array:\n",reshaped_array)

reshaped_array=array.reshape(2,3,2)
print("Reshaped array:\n",reshaped_array)


orginal array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [18]:
array_2d=np.array([[1,2,3],[4,5,6],[7, 8, 9]])
print("orginal array:\n",array_2d)

element=array_2d[1,2]
print("Element at(1,2): ",element)

subarray = array_2d[1:3, 0:2]
print("Sliced subarray:\n", subarray)

column = array_2d[:, 1]
print("Column 1:", column)

orginal array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at(1,2):  6
Sliced subarray:
 [[4 5]
 [7 8]]
Column 1: [2 5 8]


In [19]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(array)
print("Mean:", mean)

median = np.median(array)
print("Median:", median)

std_dev = np.std(array)
print("Standard Deviation:", std_dev)

min_val = np.min(array)
max_val = np.max(array)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Minimum value: 1
Maximum value: 10
